"""initial_schema

Revision ID: f839c3f848b9
Revises: 
Create Date: 2026-04-26 02:37:07.955733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f839c3f848b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('related_type', sa.String(length=32), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('uploader_role', sa.String(length=32), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=True),
    sa.Column('oss_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("file_type IN ('image','video','pdf')", name='chk_attachment_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_merchant_relations',
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','inactive')", name='chk_broker_merchant_status'),
    sa.PrimaryKeyConstraint('broker_id', 'merchant_id')
    )
    op.create_table('broker_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_no', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('specification', sa.JSON(), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','accepted','processing','completed')", name='chk_broker_task_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_person_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','suspended')", name='chk_brokers_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('signer_role', sa.String(length=32), nullable=False),
    sa.Column('signature_oss', sa.String(length=512), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contract_pdf_oss', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','signed','cancelled')", name='chk_contract_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no')
    )
    op.create_table('driver_merchant_relations',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','inactive')", name='chk_driver_merchant_status'),
    sa.PrimaryKeyConstraint('driver_id', 'merchant_id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_person_id', sa.UUID(), nullable=False),
    sa.Column('license_no', sa.String(length=32), nullable=True),
    sa.Column('license_photo_oss', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','verified','active','suspended')", name='chk_drivers_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('credit_code', sa.String(length=32), nullable=True),
    sa.Column('legal_person', sa.String(length=64), nullable=True),
    sa.Column('license_oss', sa.String(length=512), nullable=True),
    sa.Column('auth_status', sa.String(length=16), nullable=False),
    sa.Column('auth_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("auth_status IN ('pending','verified','failed')", name='chk_enterprises_auth_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gps_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transport_task_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("checkpoint_type IN ('depart','arrive_source','arrive_warehouse')", name='chk_gps_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('invoice_pdf_oss', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('api_request_id', sa.String(length=128), nullable=True),
    sa.Column('api_response', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("invoice_type IN ('REVERSE','FORWARD')", name='chk_invoice_type'),
    sa.CheckConstraint("status IN ('pending','issued','failed')", name='chk_invoice_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('merchant_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upstream_merchant_id', sa.UUID(), nullable=False),
    sa.Column('downstream_merchant_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','suspended')", name='chk_merchant_relations_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upstream_merchant_id', 'downstream_merchant_id', 'product_category_id', name='uq_merchant_relations')
    )
    op.create_table('merchant_supplier_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','blocked')", name='chk_merchant_supplier_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'supplier_id', name='uq_merchant_supplier')
    )
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enterprise_id', sa.UUID(), nullable=False),
    sa.Column('merchant_type', sa.String(length=8), nullable=False),
    sa.Column('sub_domain', sa.String(length=64), nullable=True),
    sa.Column('logo_oss', sa.String(length=512), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('allowed_product_categories', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("merchant_type IN ('C','B')", name='chk_merchants_type'),
    sa.CheckConstraint("status IN ('pending','active','suspended')", name='chk_merchants_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_domain')
    )
    op.create_table('natural_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('id_card_no', sa.String(length=18), nullable=True),
    sa.Column('id_card_front_oss', sa.String(length=512), nullable=True),
    sa.Column('id_card_back_oss', sa.String(length=512), nullable=True),
    sa.Column('auth_status', sa.String(length=16), nullable=False),
    sa.Column('auth_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("auth_status IN ('pending','verified','failed')", name='chk_natural_persons_auth_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("type IN ('order','payment','transport','system')", name='chk_notification_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('operator_role', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('payee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('channel_trade_no', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("payment_type IN ('GOODS_PAYMENT','SERVICE_FEE')", name='chk_payment_type'),
    sa.CheckConstraint("status IN ('pending','success','failed')", name='chk_payment_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('payment_no')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('spec_template', sa.JSON(), nullable=True),
    sa.Column('grade_options', sa.JSON(), nullable=True),
    sa.Column('tax_code', sa.String(length=32), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('is_hazardous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','inactive')", name='chk_product_categories_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('purchase_announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('specification', sa.JSON(), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('transport_arrangement', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','paused','closed')", name='chk_announcement_status'),
    sa.CheckConstraint("transport_arrangement IN ('BUYER','SELLER')", name='chk_announcement_transport'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('parent_order_id', sa.UUID(), nullable=True),
    sa.Column('broker_task_id', sa.UUID(), nullable=True),
    sa.Column('buyer_merchant_id', sa.UUID(), nullable=False),
    sa.Column('seller_merchant_id', sa.UUID(), nullable=True),
    sa.Column('seller_supplier_id', sa.UUID(), nullable=True),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('specification', sa.JSON(), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('resale_to_merchant_id', sa.UUID(), nullable=True),
    sa.Column('transport_arrangement', sa.String(length=16), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('plate_no', sa.String(length=16), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_source_at', sa.DateTime(), nullable=True),
    sa.Column('source_weighed_at', sa.DateTime(), nullable=True),
    sa.Column('in_transit_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_warehouse_at', sa.DateTime(), nullable=True),
    sa.Column('warehouse_weighed_at', sa.DateTime(), nullable=True),
    sa.Column('warehousing_at', sa.DateTime(), nullable=True),
    sa.Column('warehoused_at', sa.DateTime(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("order_type IN ('DIRECT','TRADE','SUB')", name='chk_order_type'),
    sa.CheckConstraint("status IN ('DRAFT','COMMITTED','DISPATCHED','ARRIVED_SOURCE','SOURCE_WEIGHED','IN_TRANSIT','ARRIVED_WAREHOUSE','WAREHOUSE_WEIGHED','WAREHOUSING','WAREHOUSED','CONTRACT_PENDING','CONTRACTED','PAYING','PAID','COMPLETED','CANCELLED')", name='chk_order_status'),
    sa.CheckConstraint("transport_arrangement IN ('BUYER','SELLER')", name='chk_transport_arrangement'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('reverse_invoice_charges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','paid')", name='chk_charge_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending','confirmed','rejected')", name='chk_commitment_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('plate_no', sa.String(length=16), nullable=False),
    sa.Column('route', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('assigned','departed','arrived_source','source_weighed','in_transit','arrived_warehouse','completed','cancelled')", name='chk_transport_task_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wx_auth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mini_program_appid', sa.String(length=64), nullable=False),
    sa.Column('open_id', sa.String(length=64), nullable=False),
    sa.Column('union_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('W','C','B','A','BROKER','DRIVER','WAREHOUSE_KEEPER')", name='chk_users_role'),
    sa.CheckConstraint("status IN ('active','suspended','deleted')", name='chk_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('warehouse_keepers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('natural_person_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('sign_authorized', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','suspended')", name='chk_warehouse_keepers_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('keeper_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('actual_weight', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','inactive')", name='chk_warehouse_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weighbridge_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('gross_weight', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('tare_weight', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('net_weight', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('actual_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_by_role', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("record_type IN ('source','warehouse')", name='chk_weighbridge_type'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weighbridge_records')
    op.drop_table('warehouses')
    op.drop_table('warehouse_receipts')
    op.drop_table('warehouse_keepers')
    op.drop_table('users')
    op.drop_table('user_wx_auth')
    op.drop_table('transport_tasks')
    op.drop_table('supply_commitments')
    op.drop_table('reverse_invoice_charges')
    op.drop_table('purchase_orders')
    op.drop_table('purchase_announcements')
    op.drop_table('product_categories')
    op.drop_table('payments')
    op.drop_table('order_status_logs')
    op.drop_table('notifications')
    op.drop_table('natural_persons')
    op.drop_table('merchants')
    op.drop_table('merchant_supplier_relations')
    op.drop_table('merchant_relations')
    op.drop_table('invoices')
    op.drop_table('gps_checkpoints')
    op.drop_table('enterprises')
    op.drop_table('drivers')
    op.drop_table('driver_merchant_relations')
    op.drop_table('contracts')
    op.drop_table('contract_signatures')
    op.drop_table('brokers')
    op.drop_table('broker_tasks')
    op.drop_table('broker_merchant_relations')
    op.drop_table('attachments')
    # ### end Alembic commands ###
